name: Sigrun
favicon: null
layout_spectrum: 0.6
typography_spectrum: 0.77027
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1e973e'
    - '#ffffff'
    - '#97ca9f'
    - '#77b47c'
    - '#437e4d'
  brandStrength: 0.75
  lightness: 0.5625
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose:
  - name: shares
    item: null
    url: null
